### PR TITLE
use quic to send transactions

### PR DESCRIPTION
**Pull request by gherkins**
An attempt so use QUIC for sending transactions...

* does get TPUs quic endpoints
* does create connection to those
* does NOT (YET) send transaction due to connection errors 

May it's "just" a cert issue, as suggested here (including code for mock cert):
https://github.com/MatrixAI/js-quic/issues/98

also posted on stackexchange....
https://solana.stackexchange.com/questions/12817/got-peer-closed-with-transport-code-306-when-trying-to-send-transaction-via-qu

### CODE REVIEW

**Comment by thealexcons** [comment]
@gherkins Any luck with the TLS errors you were encountering? I read your thread on the quic-js - would definitely be interested to hear if you get something working, or if you need any help

**Review by thealexcons — APPROVED** [review]

**Comment by lmvdz** [comment]
Let's wait to see if we can figure this out and make it work before merging the PR. 

I found some information and posted it on the other issue.

https://github.com/MatrixAI/js-quic/issues/98#issuecomment-2072467202

**Comment by lmvdz** [comment]
Do you think it's possible to send the tx's and confirm the tx at the same time using two different threads/processes?

**Comment by lmvdz** [comment]
after adding `tx.add(ComputeBudgetProgram.setComputeUnitPrice({ microLamports: 10000 }));` to my transaction I am getting a higher hit rate

**Comment by lmvdz** [comment]
> Do you think it's possible to send the tx's and confirm the tx at the same time using two different threads/processes?

Using this as a test, I was able to get the transaction confirmed, while the quic tx sending loop was still running..
perhaps we could add a AbortSignal or something to close the connections once the tx is confirmed.

```ts
import { Transaction, Keypair, SystemProgram, ComputeBudgetProgram} from '@solana/web3.js';
import { TpuConnection} from '../src/index';
import { config } from 'dotenv';
import base58 from 'bs58';

config();

// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
const rpcurl = process.env.RPC_URL!;
// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
const signer = Keypair.fromSecretKey(base58.decode(process.env.KEYPAIR!));

(async () => {
    const tpuConnection = await TpuConnection.load(rpcurl, { commitment: 'processed' });
    // console.log(tpuConnection);
    const tx = new Transaction();
    const instruction = SystemProgram.transfer({ fromPubkey: signer.publicKey, toPubkey: signer.publicKey, lamports: 1 });
    tx.add(ComputeBudgetProgram.setComputeUnitPrice({ microLamports: 10000 }));
    tx.add(instruction);
    const signature = await tpuConnection.sendTransaction(tx, [signer]);
    console.log(await tpuConnection.confirmTransaction(signature, 'confirmed'));
})();
```

**Comment by lmvdz** [comment]
I don't see how I can make my tx land faster, is the only way to increase the microLamports?

**Comment by gherkins** [comment]
i'd say the combination of low computeunits with relatively high microlamports. 

I think it's rather counterintuitive how much microlamports you actually have to put in:
https://solanacookbook.com/references/basic-transactions.html#how-to-change-compute-budget-fee-priority-for-a-transaction

Maybe something along the lines of:

```js
computeBudgetConfig: {
    microLamports: 950_000,  // 950k * 80k units =  0,000076 SOL
    units: 80_000
},
```
950_000 per compute unit * 80_000 compute units

= 76_000_000_000 total microlamports
= 76_000 total lamports (1 lamport = 1_000_000 microlamports)
= 0,000076 total SOL (1 SOL = 1_000_000_000 lamports)


that would also make for a relatively slim transaction, given the default compute units is 
`200_000 * instruction`.

also sending directly to the leader tpus should be somewhat of a factor, right?

**Comment by gherkins** [comment]
I think it's rather counterintuitive how much microlamports you actually have to put in:
https://solanacookbook.com/references/basic-transactions.html#how-to-change-compute-budget-fee-priority-for-a-transaction

950_000 per compute unit * 80_000 compute units

= 76_000_000_000 total microlamports
= 76_000 total lamports (1 lamport = 1_000_000)
= 0,000076 total SOL (1 SOL = 1_000_000_000 lamports)

**Comment by gherkins** [comment]
...as for the parallel confirmation part:

i think `connection.onSignature` is rather quick, so that should provide somewhat instant feedback, when the tx is 
processed/confirmed/finalized

```js
connection.onSignature(signature, async (result) => {
        if (result.err !== null) {
            reject(`confirmation error: ${Object.keys(result.err).join(', ')}`)
            return
        }
        resolve(signature)
    }, 'finalized')
```

but i think, as you have the signature to watch before you even send the tx, 
that this doesn't need to be in the scope of the tpu client...

you can just add the listener, then send via tpu...

**Comment by gherkins** [comment]
@lmvdz  https://github.com/MatrixAI/js-quic/pull/106
(option to provide the servername in the js quic library)

would you mind adding the cert-part of the code you figured out to this PR?

**Comment by lmvdz** [comment]
Sorry @gherkins I've been slammed with other projects. Were you able to figure it out?

**Pull request closed without merging**
